name: Generate Sphinx documentation

on:
  push:
    branches:
      - main  # Puoi cambiare il nome del ramo se necessario

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Puoi modificare la versione di Python se necessario

      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autobuild

      - name: Generate Sphinx documentation
        run: |
          sphinx-apidoc -o docs/source/modules yosoai -f

      - name: Move generated files to docs/source/modules
        run: |
          mv docs/source/yosoai* docs/source/modules
